name: dart_parser
version: 1.0.0-dev+3
description: An ANTLR-based Dart parser.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/dart_parser
dependencies:
  antlr4dart: ">=0.7.0 <1.0.0"
dev_dependencies:
  browser: ">=0.10.0 <1.0.0"
  codemirror: ">=0.4.1 <1.0.0"
  test: ">=0.12.14 <1.0.0"